### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-ecommerce#31]
Ever since adding the store, our test suite continues to fail seemingly due to the Store subfactory?
- [ ] troubleshoot the failure to resolve the current tests written up to this point

**Comment by kjcioffi** [comment]
There are test suites that are failing. If I can remember correctly, it was 6 tests that were failing in the view test suites due to incorporating FactoryBoy into the model test suites.

These issues stem from needing to use the Factories due to the custom made utility module I had deleted. Executing `py manage.py test store.tests.views.product_admin` should succeed as expected.

**Comment by kjcioffi** [comment]
Covered in #36
